### ISSUE TITLE
Image priming gives "The size of tensor a (224) must match the size of tensor b (512) at non-singleton dimension 3"

### ISSUE THREAD

**Issue by nerdyrodent** [lucidrains/deep-daze#100]
Hi,
Unless I'm missing something obvious, it looks like the image priming no longer works? E.g.

`imagine "A pizza on fire" --open_folder=False --start_image_path=./samples/prime-orig.jpg`

> siren_pytorch/siren_pytorch.py:101: UserWarning: Using a target size (torch.Size([1, 3, 512, 512])) that is different to the input size (torch.Size([1, 3, 224, 224]))
> ...
> RuntimeError: The size of tensor a (224) must match the size of tensor b (512) at non-singleton dimension 3

**Comment by jack7803m** [comment]
I'm relatively new to this so I could be wrong, but can you check what the resolution of your priming image is? It seems like you need a priming image that is the same resolution as what you're trying to output (512x512 in this case).

**Comment by nerdyrodent** [comment]
Yup! Tried images of various sizes including 224x224, 512x512 and others.

**Comment by jack7803m** [comment]
So did that not fix it? The tensor error it's giving you looks like the dimensions of the image. If you use a 512x512 priming image what error does it throw?

**Comment by nerdyrodent** [comment]
Same error every time. It can be worked around by using "--image_width=224". I'm not that great at coding, so I'm still looking through the rest of the code to see how it handles different image sizes.

**Comment by NotNANtoN** [comment]
I fixed the error that it does not run at all in the PR above (#103), but the generated images are completely white for large start_image_steps. When I checked out this repo first it already had the same issue - so now we are at least back to the old non-working version.

@nerdyrodent what you can do instead is to pass your image as `img` to the Imagine class, along with your text. Then Deepdaze will optimize for your image features too. That's quite different from image priming, but still interesting.
