### ISSUE TITLE
Story does not generate video

### ISSUE THREAD

**Issue by Fliens** [lucidrains/deep-daze#113]
I was trying to recreate the example:
![image](https://user-images.githubusercontent.com/35639879/112758516-1d82d000-8fef-11eb-8330-c40207939295.png)

But it did not generate the video. Is the video made in post or is deep-daze able to generate it?

It would also be nice if you could add the exact command the example was made with :)

**Comment by NotNANtoN** [comment]
Hi, sorry about the lack of information. I just quickly put that together.

The video is created in post by stitching all generated frames together with a command such as: `ffmpeg -i "INPUT_TEXT.000%03d.jpg" -pix_fmt yuv420p movie.mp4`

Unfortunately, I do not remember the exact command but something like this should work:
`imagine POEM_TEXT --num_layers 44 --batch_size 32 --create_story 1 --save_every 20 --image_width 256`

Let me know if it works!
