### ISSUE TITLE
Working on the project

### ISSUE THREAD

**Issue by Fliens** [lucidrains/deep-daze#124]
Hi I really wanto to contribute to this project but I'm having some difficulties

I'm using vscode and I've already cloned the project(locally, not in conda) but I'm having difficulties running the project in the console.
I've already switched the interpreter to conda but it seems like it's not working

I want to work on the stories so that the text is splitted by a separator and not every 5 words or so:)

**Comment by NotNANtoN** [comment]
Well, what's your error message? I assume you installed all requirements? Furthermore, make sure you have torch version 1.7.1.

**Comment by Fliens** [comment]
I think I got it to run
The problem was that I tried to run it with the wrong python.exe
But through finding the python.exe in the conda env and the executing the project with that .exe it worked

But now I'm getting this error:

`from .clip import load, tokenize 
ImportError: attempted relative import with no known parent package`

**Comment by NotNANtoN** [comment]
That might be a good place to start contributing! ;)

I think this line should have the full path: `from deep_daze.clip import load, tokenized `

For me it works as it is, but Windows might have some problems there.
