### ISSUE TITLE
[Suggestion] Begin with encoded image / implicit neural representation of user image

### ISSUE THREAD

**Issue by torridgristle** [lucidrains/deep-daze#13]
From what I can tell, SIREN should be very capable of encoding a supplied bitmap image to an implicit neural representation. I haven't figured out how to do it myself yet, but the ability to begin a session of deep-dazing with a specific image, to some level of completion with encoding to INR), should be very helpful with guiding the image generation or perhaps even image modification. Or old Deep Dream style hallucinations.

[Rambling]
One of the first things I tried to do with the original notebook was make an emote. Well, it didn't work. It made a hazy half-remembered dream image of a screen with non-descript emotes on it. Then I realized if I stopped the training, and didn't generate a network, I could swap out the CLIP prompt and steer the ship so to speak. From there it was trying to get it to generate a yellow circle, orb, or ball, and that wasn't happening.

But what if it could begin with an image of a yellow circle? Or a yellow circle with eyes and a mouth? Would it manage to make an emote out of it when prompted "visceral nightmare emoji"? Or would it cover it the yellow circle with strange shapes that have little to do with the supplied image or structure? I don't actually know. But at the very least it may end up with an aesthetic like the old Deep Dream putting eyes and spider legs on everything.

Or perhaps something to force the generation to follow certain shapes by warping the initial -1 to 1 2D grid / mgrid that was in the old notebook.

**Comment by lucidrains** [comment]
@torridgristle if you can show me a notebook where it works, i'll consider adding it as a feature!

**Comment by torridgristle** [comment]
I got it figured out to the point where I can supply it with a saved INR from the Explore Siren demo modded for RGB and have it transform an image.

![Compare-levels](https://user-images.githubusercontent.com/23273466/105224616-6324a780-5b2b-11eb-8728-143be6154813.jpg)

[SIREN and CLIP image loading.zip](https://github.com/lucidrains/deep-daze/files/5844810/SIREN.and.CLIP.image.loading.zip)

I haven't put them together, there's so much shit that it's overwhelming, but with these two notebooks you load RGB Mod explore_siren and change `img = Image.open("/content/smileman.jpg")` in the Experiments section to be whatever image you want, and change `img_siren = Siren(in_features=2, out_features=3, hidden_features=256, hidden_layers=3, outermost_linear=True)` from the code cell 2 cells down to whatever number of hidden features and layers you want (I just kept it default). Let it run the training for a while until it's good enough, and then run `torch.save(img_siren, 'test-smileman-rgb.pkl')` to save the INR.

Next you open the ImageLoading CLIP and SIREN notebook, upload the INR to `/content/`, and in the SIREN section at the end of the code cell there's `model = torch.load("/content/sirennet-smileman-rgb.pkl").cuda()` and you just swap that filename out for whatever you want, and from there it should work fine if you run it like normal.

Also there's some other small changes like iterations and swapping normalize for a denormalize thing I saw in a fork somewhere that seemed to get me somewhat better colors from Deep Daze but when it's starting from an INR of an image it's real faded and yellow/green.

**Comment by afiaka87** [comment]
> Also there's some other small changes like iterations and swapping normalize for a denormalize thing I saw in a fork somewhere that seemed to get me somewhat better colors from Deep Daze but when it's starting from an INR of an image it's real faded and yellow/green.

Hey, yeah I wrote that small change as an experiment. That yellow/green fade is just the opposite effect of the blue/black fade you get otherwise. I suggest removing it until we figure out what the real problem is with the coloring. 

https://github.com/lucidrains/deep-daze/issues/9#issuecomment-763266365

**Comment by afiaka87** [comment]
@torridgristle do you mind me asking what text phrase you used to get that horrifying output btw?

**Comment by torridgristle** [comment]
"angry man"

**Comment by afiaka87** [comment]
> Then I realized if I stopped the training, and didn't generate a network, I could swap out the CLIP prompt and steer the ship so to speak.

Oh, wow. Being able to say in advance "at epoch 5, run this phrase, at epoch 10 run this phrase, at epoch 15 run this phrase" would be awesome! How well did it work in practice @torridgristle ?

**Comment by torridgristle** [comment]
> Oh, wow. Being able to say in advance "at epoch 5, run this phrase, at epoch 10 run this phrase, at epoch 15 run this phrase" would be awesome! How well did it work in practice @torridgristle ?

I ain't bothered with it much. It didn't really keep much from the past image apart from perhaps a general layout but since it mostly generates lots of tiny things, which I suppose is related to the ascend_txt() function doing a lot of random crops of the image for CLIP to detect objects in, there's not much of a layout to be had and the few times I used it I didn't notice any cool morphing. Perhaps if I could get CLIP to work better with larger crops of the image or focus on a certain area of the image it could generate larger objects instead of ~10px ones, but good and bad results seemed unrelated to my changes lol.
Sometimes I could get things a little bigger and they'd be reasonably well-formed.
![Rich Evans Mike Stoklasa](https://user-images.githubusercontent.com/23273466/105614696-ea2a8780-5d98-11eb-97e2-5563935b9a05.png)
Sometimes it's clown vomit.
![Rich Evans Mike Stoklasa (1)](https://user-images.githubusercontent.com/23273466/105614719-08908300-5d99-11eb-9833-fd8f3d7b4f63.png)
Sometimes it looks like it developed the higher frequency details and edges of the prompt's subject, but not the lower frequency information like swathes of colors.
![Rich Evans Mike Stoklasa (2)](https://user-images.githubusercontent.com/23273466/105614727-12b28180-5d99-11eb-98e5-3ff2e0f35861.png)
And sometimes there's just too many overlapping Rich Evans / Mike Stokalasas in the same place.
![Rich Evans Mike Stoklasa (3)](https://user-images.githubusercontent.com/23273466/105614743-383f8b00-5d99-11eb-8429-24afbdccfb43.png)


Starting from an encoded image has more of a morph to it but could be improved as well, especially if there's very clear boundaries like in the example I'll post below.

Original Rick Astley face, a handsome babyfaced boy.
![rickastley256](https://user-images.githubusercontent.com/23273466/105614545-1eea0f00-5d98-11eb-8d31-69118dcec628.jpg)
"H.R. Giger singer songwriter"
![H R  Giger singer songwriter](https://user-images.githubusercontent.com/23273466/105614559-34f7cf80-5d98-11eb-9be6-6360c0efab2b.png)
"Hideo Kojima"
![Hideo Kojima](https://user-images.githubusercontent.com/23273466/105614575-4640dc00-5d98-11eb-835a-dc91bead12df.png)
"Face"
![Face (5)](https://user-images.githubusercontent.com/23273466/105614581-4fca4400-5d98-11eb-9111-20e705576dec.png)
"Face"
![Face (2)](https://user-images.githubusercontent.com/23273466/105614586-55c02500-5d98-11eb-8f58-6ed9bb318a4c.png)
"Alien parasite body horror" I was also fucking with gamma adjustments to the data sent to CLIP, I don't remember what was in place at the time of this render but I squared something before or after the nom with the CLIP dataset's mean and stdev or norm that just scaled it to 0-1.
![Alien parasite body horror](https://user-images.githubusercontent.com/23273466/105614594-5e186000-5d98-11eb-9ed2-d85f237e530b.png)
"Face"
![Face](https://user-images.githubusercontent.com/23273466/105614663-a899dc80-5d98-11eb-97f8-ebe1f26942e7.png)
"Rich Evans Mike Stoklasa"
![Rich Evans Mike Stoklasa (6)](https://user-images.githubusercontent.com/23273466/105614675-bbacac80-5d98-11eb-87c7-b51252722fcf.png)

**Comment by lucidrains** [comment]
https://github.com/lucidrains/deep-daze#priming
