### ISSUE TITLE
INCREDIBLY slow performance on 5700xt

### ISSUE THREAD

**Issue by Not-AriStienfeld** [lucidrains/deep-daze#154]
Hi, it looks like my windows powershell is simply not using my 5700xt, despite deepdaze saying it works with amd GPUs
![image](https://user-images.githubusercontent.com/56319363/126856254-8ccd8ca1-956c-4e16-9317-ddc7cc4bbfe3.png)
does anyone know how to get it to use my gpu instead of my cpu?

**Comment by evan203** [comment]
Hi, 

I am also experiencing this on a rx 5700xt. I am using archlinux and just installed deep-daze using pip3.
![image](https://user-images.githubusercontent.com/63885438/138379600-59dafb3e-315a-47dc-8132-6c0124ab4427.png)

my gpu usage is between 1-5% which is idle for my system, however see that it is using quite a bit of my cpu (100% on about 6 threads) which means that's obviously what the case is.

**Comment by evan203** [comment]
https://github.com/lucidrains/deep-daze/blob/25ac9f445e5532f72ee48ebbe61ce560a258422f/deep_daze/deep_daze.py#L340

This whole algorithm is built on CUDA, so I don't get why the readme mentions it working on AMD  cards, which don't have CUDA. I guess this closes the issue
