### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.6/dist-packages/deep_daze/data/bpe_simple_vocab_16e6.txt'

### ISSUE THREAD

**Issue by Vaibhav21pandit** [lucidrains/deep-daze#2]
**I'm trying this out in colab and facing the above error**.Here's the full stack:
Traceback (most recent call last):
  File "/usr/local/bin/imagine", line 5, in <module>
    from deep_daze.cli import main
  File "/usr/local/lib/python3.6/dist-packages/deep_daze/__init__.py", line 1, in <module>
    from deep_daze.deep_daze import DeepDaze, Imagine
  File "/usr/local/lib/python3.6/dist-packages/deep_daze/deep_daze.py", line 11, in <module>
    from deep_daze.clip import load, tokenize, normalize_image
  File "/usr/local/lib/python3.6/dist-packages/deep_daze/clip.py", line 223, in <module>
    _tokenizer = SimpleTokenizer()
  File "/usr/local/lib/python3.6/dist-packages/deep_daze/clip.py", line 64, in __init__
    merges = Path(bpe_path).read_text().split('\n')
  File "/usr/lib/python3.6/pathlib.py", line 1196, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/usr/lib/python3.6/pathlib.py", line 1183, in open
    opener=self._opener)
  File "/usr/lib/python3.6/pathlib.py", line 1037, in _opener
    return self._accessor.open(self, flags, mode)
  File "/usr/lib/python3.6/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.6/dist-packages/deep_daze/data/bpe_simple_vocab_16e6.txt'

**Comment by lucidrains** [comment]
@Vaibhav21pandit hello! want to try 0.1.7? :crossed_fingers:

**Comment by forkbabu** [comment]
@Vaibhav21pandit how did you run cuda10.2 stuff in colab? I get an error that pytorch and torchvision both have to be in cuda10.2

**Comment by forkbabu** [comment]
@lucidrains can u drop a colab demo ? running 10.2 stuff on colab is difficult fr noobs like me. will tell u to close this issue if my colab nb successfully works with ur latest release.

**Comment by forkbabu** [comment]
@lucidrains  on colab 

```
/usr/local/lib/python3.8/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 10010). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at  /opt/conda/conda-bld/pytorch_1607369981906/work/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
Traceback (most recent call last):
  File "/usr/local/bin/imagine", line 5, in <module>
    from deep_daze.cli import main
  File "/usr/local/lib/python3.8/site-packages/deep_daze/__init__.py", line 1, in <module>
    from deep_daze.deep_daze import DeepDaze, Imagine
  File "/usr/local/lib/python3.8/site-packages/deep_daze/deep_daze.py", line 16, in <module>
    assert torch.cuda.is_available(), 'CUDA must be available in order to use Deep Daze'
AssertionError: CUDA must be available in order to use Deep Daze
```
`!pip list | grep torch`
```
siren-pytorch     0.0.6
torch             1.7.1
torchvision       0.8.2
```

**Comment by lucidrains** [comment]
@forkbabu i updated the readme with colab links!

**Comment by Vaibhav21pandit** [comment]
> @Vaibhav21pandit how did you run cuda10.2 stuff in colab? I get this error -> https://stackoverflow.com/questions/63062741/pytorch-and-torchvision-are-compiled-different-cuda-versions

upgrade your torchvision separately that should solve this

**Comment by Vaibhav21pandit** [comment]
> @Vaibhav21pandit hello! want to try 0.1.7? crossed_fingers

sure, will try and get back

**Comment by Vaibhav21pandit** [comment]
Just checked out the simplified notebook with the torchvision+cu101 works flawlessly.Thanks for this implementation @lucidrains
