### ISSUE TITLE
Are the photos in the README file copyright?

### ISSUE THREAD

**Issue by Atompunk78** [lucidrains/deep-daze#205]
As the title says; I'm making a youtube video about AI art and I'd like to use them in it. It's very unlikely the video will make any money but I can't guarantee it won't.

**Comment by Atompunk78** [comment]
I'm sorry if this isn't the correct way to ask such a question, I haven't used github much and I couldn't find any other way to ask.

**Comment by geeknik** [comment]
I'm not a copyright lawyer and I'm not expert in software licenses, but I believe the repositories MIT License covers the images in the README.md, which means as long as you follow the MIT license, you're good to go, but I'll defer to a more knowledgeable party.

**Comment by Atompunk78** [comment]
Right, that sounds pretty reasonable. The README _is_ part of the software and the MIT license covers all of the software, so it should be ok. Thanks!

For anyone seeing this that wants to copyright claim me, my youtube channel is Atompunk78, please don't cease and desist / sue / copyright claim me, just message me personally and I'll take it down if there's an issue.
