### ISSUE TITLE
Deep Daze vs Big Sleep?

### ISSUE THREAD

**Issue by himat** [lucidrains/deep-daze#29]
Just checking but Deep Daze and Big Sleep have the same goal except for the use of the image generation model right?

Have you been able to determine whether SIREN or BigGAN is better for generating better / higher quality images?

**Comment by afiaka87** [comment]
I think you're looking for a more rigorous answer than this, but until that comes in, here's some discussion on the differences. 

https://github.com/lucidrains/deep-daze/issues/19

Speaking from personal experience, big-sleep _can_ be more impressive, but it seems to require finicky parameters to get it to work great. 

deep-daze is way more consistent, but more abstract. The results you get tend to be pretty similar if you rerun it on a given phrase.  Basically always looks mildly stylized/cartoonish unless you specify certain texturing in your phrase. 

big-sleep seems to run fine under 16 GiB of vram. I'm not sure what the parameters are for big-sleep, but I don't think you can change the number of hidden layers. With deep-daze you can crank hidden_layers to 128 if you've got more than just a colab  instance. There are diminishing returns at around 50 layers, as far as I can tell.
