### ISSUE TITLE
Not sure if this is an easy fix or not

### ISSUE THREAD

**Issue by KinGJIII** [lucidrains/deep-daze#33]
I've left my PC a few times but left it to keep rendering, but it stops sometimes, and only resumes when i press enter. Is there a way to circumvent this and have it run all the time?

**Comment by afiaka87** [comment]
Have you tried since the 0.3.5 release yesterday? I accidentally committed a nasty bug that broke it if you used the save-every/save-progress parameters.

**Comment by KinGJIII** [comment]
Yup! Problems been eleminated!
