### ISSUE TITLE
Files overwritten after each epoch

### ISSUE THREAD

**Issue by afiaka87** [lucidrains/deep-daze#35]
**Bug**: Images saved with --save_every have the incorrect sequence number and start to overwrite themselves after each epoch. 

This one's my bad again. I re-wrote the code for this and made the mistake of using the iteration instead of `self.iterations * epoch + iteration // self.save_every` for the filename sequence number. 

Here's a PR that should fix it. 

https://github.com/lucidrains/deep-daze/pull/34

**Comment by lucidrains** [comment]
merged! thanks!
