### ISSUE TITLE
p(image | text)

### ISSUE THREAD

**Issue by volkancirik** [lucidrains/deep-daze#4]
Hello,

is it possible to get the log propability of a generated image given text using this model?

**Comment by lucidrains** [comment]
@volkancirik Hi! You can derive that using https://github.com/openai/CLIP , which is just one component of Deep Daze!

**Comment by volkancirik** [comment]
Unfortunately, CLIP does not provide such calculation but potentially DALL-e or maybe deep-daze can.

**Comment by lucidrains** [comment]
@volkancirik ohh you are right, I wasn't thinking straight

i believe the best way would be to get onboard replication efforts for https://github.com/lucidrains/DALLE-pytorch
