### ISSUE TITLE
Colab Display Doesn't Work

### ISSUE THREAD

**Issue by afiaka87** [lucidrains/deep-daze#5]
It seems the "display" feature isn't working in COLAB and is generating URL's expecting a base64 format, but with only the filename appended. 

For instance: "data:image/png;base64,./8bitvideogame.png"

**Comment by afiaka87** [comment]
For now, I've gotten this to work by simply doing a manual `TEXT.replace(" ", "-")` so that the filename matches the one that gets stored by deep-daze.

```python
filename = TEXT.replace(" ", "_") + ".png"

image = Image(filename)
display(image)
```

I think exposing the filename you use in the Imagine code would probably be a better fix though.

**Comment by afiaka87** [comment]
Ah I see, this must have been an issue of updating deep-daze in pip, but not updating the colab notebook. 

https://github.com/lucidrains/deep-daze/blob/81d1b80337ee7e62adbf7cea84bbb4c6d2c893c9/deep_daze/deep_daze.py#L186

The original colab notebook worked with spaces in filenames. Deep-daze was changed to change spaces to dashes, breaking the colab notebook. I suggest either the above change to the colab notebook, or exposing the "filename" from the Imagine class somehow.

**Comment by lucidrains** [comment]
@afiaka87 should be fixed!

**Comment by afiaka87** [comment]
Awesome! Thanks again.
