### ISSUE TITLE
CLI is broken - "missing 1 required positional argument: 'name'"

### ISSUE THREAD

**Issue by afiaka87** [lucidrains/deep-daze#51]
Usage:
```
imagine "phrase"
```

Output:
```bash
imagine "tacos"
TypeError: __init__() takes 1 positional argument but 2 positional arguments (and 18 keyword-only arguments) were given
```

**Comment by afiaka87** [comment]
Whoops, nevermind. This was an issue I was having on a separate branch of mine.

**Comment by afiaka87** [comment]
I've fixed the bug (and added the ability to choose between the ViT-B/32 or RN50 models of CLIP) in this pull request.

https://github.com/lucidrains/deep-daze/pull/52

**Comment by afiaka87** [comment]
Having a little trouble with the CLIP model code. Here's a PR with _just_ the CLI fix (it's one line in cli.py).

https://github.com/lucidrains/deep-daze/pull/53

**Comment by NotNANtoN** [comment]
Hey, I'm sorry. I introduced this because I changed the text to be optional in my PR. I did not test the CLI and thought someone would check it. It surprised me that the PR was merged directly - but now I know. Next time I'll check more thoroughly!

**Comment by afiaka87** [comment]
> Hey, I'm sorry. I introduced this because I changed the text to be optional in my PR. I did not test the CLI and thought someone would check it. It surprised me that the PR was merged directly - but now I know. Next time I'll check more thoroughly!

No problem. The versioning probably mitigated it to a degree. Having said that, @lucidrains it might be good to remove the pip --upgrade call in your colab notebook.
