### ISSUE TITLE
Add ability to use RN50 CLIP model

### ISSUE THREAD

**Issue by afiaka87** [lucidrains/deep-daze#54]
Working on this currently. Should have PR up by end of day.

**Comment by mroosen** [comment]
Thanks! Did you see any fancy improvements in the generated images?

**Comment by afiaka87** [comment]
Honestly, so far not really. Maybe _slightly_ more detail? But I think this will be more beneficial for phrases closer to the 77 char limit. At any rate, this will let folks at least explore with it.

**Comment by afiaka87** [comment]
They've cryptically hinted that a much larger model will be released "soon" as well. On their github issues.

**Comment by mroosen** [comment]
Yeah, I hope they'll release it soon. Not sure if there's a big memory impact though. I've been trying lengthy paragraphs too, to see how those are handled. Often they actually lead to pretty nice results, so I can't wait for the bigger CLIP models then.

**Comment by afiaka87** [comment]
Well, I'm giving up on implementing this properly for now. Keep getting floating point errors whenever I pull the CLIP perceptor inside of the Imagine class and try to pass it to DeepDaze for it to use as well. 

Anyway, here's a branch with literally just the url in the clip.py file changed to be RN50.

https://github.com/afiaka87/deep-daze/tree/just_rn50

You can install it directly with `pip install git+https://github.com/afiaka87/deep-daze.git@just_rn50`

**Comment by NotNANtoN** [comment]
Why do you expect the RN50 to perform better? I only see that it has fewer parameters and that it performs worse on zero-shot classification than the available vision transformer (from the paper).

Also, I think it might be smart to change the way CLIP is being used by actually importing the clip library. That would eliminate a lot of CLIP-related code in deepdaze and make it much more maintainable as newer models are released.

**Comment by afiaka87** [comment]
I was not aware that it was ill-performing, thanks. I agree that we should import the clip library. Unfortunately, due to an exisiting library named `clip` already in pip, you have to install it using something like -

```python
# setup.py
setup(
...
  install_requires=[
     'clip @ git+https://github.com/openai.git'
  ]
)
```

Although I haven't quite been able to get it to work. Keeps failing out and installing the wrong `clip`.
