### ISSUE TITLE
Add Fourier Feature Mapping for Improved Quality

### ISSUE THREAD

**Issue by afiaka87** [lucidrains/deep-daze#59]
A pal of mine discovered a fantastic notebook by a coder using the Github handle eps696. The notebook adds fourier feature mapping to CLIP+SIREN to great effect. 

Here's the [Original Notebook](https://colab.research.google.com/drive/1L14q4To5rMK8q2E6whOibQBnPnVbRJ_7) and here's 
[My Custom Version](https://colab.research.google.com/gist/afiaka87/e018dfa86d8a716662d30c543ce1b78e/text2image-siren.ipynb) with some fun additions such as prompts to minimize (`subtract`) and a prompt for painting `finer details`. All due credit, those ideas are also from eps696 in another of their notebooks.

Anyway, it definitely seems to help. Using as few as 16 SIREN layers, I've gotten this output:

`cosmic love and attention`
https://user-images.githubusercontent.com/3994972/109033636-77a91200-768c-11eb-8d5c-265f745cf496.mp4

`mist over green hills`
![vlcsnap-2021-02-24-11h49m43s175](https://user-images.githubusercontent.com/3994972/109042973-6bc24d80-7696-11eb-9428-7fda9f6494fe.png)

`mist over green hills` with the `fine_details="trees"`
![mist_fine_detail](https://user-images.githubusercontent.com/3994972/109042506-e5a60700-7695-11eb-8429-c7dcb5f24e46.jpeg)

The drawbacks seem to be that the learning rate is much more fickle and may even need to be changed slightly on a per-phrase basis (if you get really unlucky). Increasing the number of SIREN layers to anything more than 20 causes lots of issues as well and I'm pretty unclear as to why that is. I can't find a stable learning rate for those. Also, there is a `fourier_scale` parameter which eps696 left at 4, but I've found 2 to be a better result.

**Comment by NotNANtoN** [comment]
Can you explain what it does, precisely? Looks nice! It would be interesting to compare it to the generations of the new size schedule of #61 and to combine it.

**Comment by afiaka87** [comment]
I can not! Unfortunately my expertise in machine learning is quite limited. I just found the notebook and saw the generations were indeed quite nice. Looking at your output though, I think the primary contributor to the quality of the latter image is just that I have the `fine_details` prompt enabled. It's probably worth looking into implementing that feature as well.

I'll do some comparisons when I get time, but for now I think you've "solved" this issue through other means.
