### ISSUE TITLE
Colab Notebook Overwrites Each Saved Image

### ISSUE THREAD

**Issue by afiaka87** [lucidrains/deep-daze#6]
As it stands, the colab notebook is saving each iteration's image as the same filename. This causes the previous iteration to be lost. A simple change of this line -

`image = Image(f'./{TEXT}.png')`

to

`image = Image(f'./{TEXT}-{i}.png')`

is a reasonable fix. This works bc the variable `i` holds the current iteration.

**Comment by afiaka87** [comment]
My mistake, it appears the file saving logic is happening inside of the `Imagine` class. Fixing it from Colab itself doesn't seem to be possible. I'll start looking into where the saving logic is in this codebase and see if there isn't a way to have an id appended before saving.

**Comment by afiaka87** [comment]
https://github.com/lucidrains/deep-daze/blob/81d1b80337ee7e62adbf7cea84bbb4c6d2c893c9/deep_daze/deep_daze.py#L186

This line is where the string is generated. Is there any reason the iteration count couldn't be appended here as well?

**Comment by lucidrains** [comment]
@afiaka87 I fixed this in the latest version! try  using the `--save-progress` flag

**Comment by afiaka87** [comment]
Perfect! Thanks. Keep up the good work.
