### ISSUE TITLE
create_story not working

### ISSUE THREAD

**Issue by Gyrozaid** [lucidrains/deep-daze#69]
Has anyone been able to use create_story with the colab notebooks? If so, how'd you do it? I can't get it to train past the first phrase

**Comment by NuclearSurvivor** [comment]
to be honest it was easier to just download it on my pc than it was to use colab

**Comment by afiaka87** [comment]
> to be honest it was easier to just download it on my pc than it was to use colab

That's not a useful response. Some people dont have enough vram to run this software and rely on colab; it's an understandable situation. 

Having said that, I'm quite distracted at the moment and a project @NotNANtoN is still managing relies on the feature. Perhaps they can provide more insight.

**Comment by Gyrozaid** [comment]
> > to be honest it was easier to just download it on my pc than it was to use colab
> 
> That's not a useful response. Some people dont have enough vram to run this software and rely on colab; it's an understandable situation.
> 
> Having said that, I'm quite distracted at the moment and a project @NotNANtoN is still managing relies on the feature. Perhaps they can provide more insight.

No worries, I've since figured it out :)

**Comment by NuclearSurvivor** [comment]
> > to be honest it was easier to just download it on my pc than it was to use colab
> 
> That's not a useful response. Some people dont have enough vram to run this software and rely on colab; it's an understandable situation.
> 
> Having said that, I'm quite distracted at the moment and a project @NotNANtoN is still managing relies on the feature. Perhaps they can provide more insight.

I was referencing my experience with it; I had a lot of difficulty with trying to use colab and found it easier to download it on my pc, was not trying to mislead you into thinking that I was saying to just download it by saying that. But yes that was a rather useless response

**Comment by NotNANtoN** [comment]
> Has anyone been able to use create_story with the colab notebooks? If so, how'd you do it? I can't get it to train past the first phrase

@Gyrozaid what was the issue? If it's some complication that other users might also have, please share it :)

**Comment by Gyrozaid** [comment]
> > Has anyone been able to use create_story with the colab notebooks? If so, how'd you do it? I can't get it to train past the first phrase
> 
> @Gyrozaid what was the issue? If it's some complication that other users might also have, please share it :)

I was attempting to loop through epochs and iterations using the code in the example notebook and was trying to use
update_story_encoding to get the model to change the text that it was learning on. For some reason it wouldn't update the text, until I realized I didn't have to loop through epochs and iterations, I could just use model() to run the model and it works. So the solution is to just ditch the code in the notebook and use model() instead of looping through epochs and iterations.
