### ISSUE TITLE
Colab - pip install --upgrade might be best

### ISSUE THREAD

**Issue by afiaka87** [lucidrains/deep-daze#7]
`!pip install --upgrade deep-daze`

I think this is more appropriate considering this is an instance of Colab usage in which people are explicitly restarting the kernel to use cached versions (and since you are apparently quite active still with your updates). 

For me, specifically, I didn't know why the `save_progress` kwarg wasn't available until I realized I needed to update.

There may be downfalls to this approach though as well. Benefits to pinned versions n' all that. Just a suggestion.

**Comment by lucidrains** [comment]
@afiaka87 ok done!
