### ISSUE TITLE
imagine not recognised after install?

### ISSUE THREAD

**Issue by EloniX-X** [lucidrains/deep-daze#76]
.

**Comment by NuclearSurvivor** [comment]
you need to install deep daze lol

**Comment by afiaka87** [comment]
Does that mean something like
```IPython
%tensorflow_version 1.x
%pip install torch==1.8.0+cu111 torchvision==0.9.0+cu111 torchaudio===0.8.0 -f https://download.pytorch.org/whl/torch_stable.html
%pip install --upgrade CLIP
```

%pip install deep-daze --upgrade

**Comment by NuclearSurvivor** [comment]
> Does that mean something like
> 
> ```
> %tensorflow_version 1.x
> %pip install torch==1.8.0+cu111 torchvision==0.9.0+cu111 torchaudio===0.8.0 -f https://download.pytorch.org/whl/torch_stable.html
> %pip install --upgrade CLIP
> %pip install deep-daze --upgrade
> ```
> 
> would be required in the colab notebook now? @lucidrains
> 
> Edit: also, if you do get around to changing it, there's a bug in the display code now that deep-daze saves jpg instead of png.
> 
> ```python
> for epoch in trange(20, desc = 'epochs'):
>     for i in trange(ITERATIONS, desc = 'iteration'):
>         model.train_step(epoch, i)
> 
>         if i % model.save_every != 0:
>             continue
> 
>         filename = TEXT.replace(' ', '_')
>         image = Image(f'./{filename}.jpg') # This line
>         display(image)
> ```

Yes, those were the steps I took, and the upgrade commands I put all needed to be updated, and either way it's just making sure you have to most up-to-date versions.
