### ISSUE TITLE
Can We Put a VRAM warning at the top of the README?

### ISSUE THREAD

**Issue by afiaka87** [lucidrains/deep-daze#86]
I have no idea where all this new traffic is coming from, but we've had like 4 posts in the past few days about trying to run this on consumer graphics cards. I think **putting a note at or near the top of the README** would be good at helping some of these folks. As it stands, the GPU optimizations are pretty far down a wall of text, so I can't exactly blame them for not getting to it. Maybe just something like:

> FAQ:
> Q: I keep trying to run this and it's giving me an error about not having enough memory. What gives?
> A: This program requires a lot of VRAM. If you're trying to run it with less than 16 GB of VRAM on your card, please scroll down to see some options you can tinker with. In general, setting `--image_width=256` will probably fix your problem if you have ~6-8 GB of VRAM. If you have less, then it's probably going to be impossible to run this program unfortunately.

**Comment by afiaka87** [comment]
You could put a similar warning on big-sleep. As it stands, that program _just barely_ blows 8 GiB I think. So a lot of people will be able to run it actually but they'll have to settle for an `--image_size=256`.

**Comment by jack7803m** [comment]
Not that it matters very much to the issue itself, but if you are curious, I believe a lot of this traffic is coming from TikTok. I've seen several people post about the program (each video with 30k+ likes), and they all just leave out how intensive it is to run, so adding a warning right at the top would be great.

**Comment by afiaka87** [comment]
> Not that it matters very much to the issue itself, but if you are curious, I believe a lot of this traffic is coming from TikTok. I've seen several people post about the program (each video with 30k+ likes), and they all just leave out how intensive it is to run, so adding a warning right at the top would be great.

Ah, that explains it. Thanks, I actually was kinda curious.

**Comment by RaymondTerry** [comment]
Hello, I am currently a university student looking for projects to contribute to. This project is very fascinating to me and the warning would also apply to my current setup as well seeing as I only have a GTX 1650 SUPER. Would it be okay if I make the the warning for the VRAM usage more apparent in the README file?

**Comment by afiaka87** [comment]
That will be up to @lucidrains who I'm afraid is _very_ busy currently with other projects. Thanks for the contribution though - we'll hopefully get around to merging it soon.
