### ISSUE TITLE
settings for examples

### ISSUE THREAD

**Issue by Mearman** [lucidrains/deep-daze#91]
sorry didn't know where to put this other than an issue.

if you can remember, would you mind sharing the settings you used to generate the results shown in the readme? I haven't yet been able to develop anything of that quality yet. I get to about 50 images in and it doesn't improve much more.

**Comment by NotNANtoN** [comment]
Hi! 

I created those examples. I used an image size of 256, 44 layers and a batch size of 32 for 8 epochs.

Let me know if that helps!

**Comment by Mearman** [comment]
Perfect. Thank you.
