### ISSUE TITLE
Change GPU

### ISSUE THREAD

**Issue by MrRyanator** [lucidrains/deep-daze#93]
I am playing around with this on a laptop and it has an integrated intel graphics card along side a RTX 2060. By default it's selecting the integrated graphics (GPU 0), and I cannot figure out how to direct it to the RTX card (GPU 1).

**Comment by RoyLJH** [comment]
How do you fix that?

**Comment by zacharyqueralt** [comment]
did you manage to fix it, im having a similar issue with two GPUs
