### ISSUE TITLE
a very small advice

### ISSUE THREAD

**Issue by mikelty** [lucidrains/deep-daze#97]
in the notebook, there's this package called tqdm.notebook. so instead of ```from tqdm import XXX``` use ```from tqdm.notebook import XXX```. this would make the progress bar much cleaner as vanilla tqdm prints a line for every epoch trained in colab. 

also the image is not displaying in colab for some reason. so i changed 'png' to 'jpg' in the filename and checked the save progress button.

**Comment by lucidrains** [comment]
@mikelty updated Mike! let me know if that works for you!

**Comment by mikelty** [comment]
yeah i think so thanks.
